source "https://rubygems.org"

# Declare your gem's dependencies in authorization.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

path '..' do
  gem 'core'
end

# KT TODO: these are brought manually over from the Core component, because I don't believe we have these fancy
# custom options for Gemspec files:
gem 'queue_classic', :github => 'Chorus/queue_classic'
gem 'chorusgnip', :github => 'Chorus/gnip'

gem 'rspec-rails', '2.99.0'
gem 'shoulda-matchers'
gem 'factory_girl'
gem 'fixture_builder'
gem 'timecop'
gem 'rr'
gem 'sunspot_rails'
gem 'hashie'
gem 'sunspot_matchers'
