require "authorization/engine"

module Authorization

  ROLE_PERMISSIONS = {

    'admin' => {
      'Events::Base' => %w(create show update destroy create_comment_on create_attachment_on),
      'Role' =>         %w(create show update destroy manage_application_roles manage_workspace_roles),
      'ChorusScope' =>  %w(create show update destroy manage_scopes),
      'User' =>         %w(create show update destroy change_password edit_dashboard manage_notifications manage_comments manage_notes manage_insights manage_data_source_credentials ldap),
      'Account' =>      %w(create show update destroy change_password lock unlock),
      'Group' =>        %w(create show update destroy),
      'Workspace' =>    %w(create show update destroy admin create_workflow edit_settings add_members delete_members add_to_scope remove_from_scope add_sandbox delete_sandbox change_status add_data remove_data explore_data transform_data download_data),
      'DataSource' =>   %w(create show update destroy add_credentials edit_credentials delete_credentials add_data remove_data explore_data download_data),
      'Note' =>         %w(create show update destroy create_attachment_on demote_from_insight),
      'Schema' =>       %w(create show update destroy),
      'Sandbox' =>      %w(create show update destroy add_to_workspace delete_from_workspace),
      'Comment' =>      %w(create show update destroy promote_to_insight),
      'Workfile' =>     %w(create show update destroy create_workflow run_workflow),
      'Workflow' =>     %w(create show update destroy run stop open),
      'Job' =>          %w(create show update destroy run stop),
      'Task' =>         %w(create show update destroy run stop),
      'Milestone' =>    %w(create show update destroy complete restart),
      'Tag' =>          %w(create show update destroy apply remove),
      'Upload' =>       %w(create show update destroy),
      'Import' =>       %w(create show update destroy),
      'Notification' => %w(create show update destroy),
      'CsvFile' =>      %w(create show update destroy)
    },

    'owner' => {
      'Events::Base' => %w(create show update destroy create_comment_on create_attachment_on),
      'Role' =>         %w(create show update destroy manage_application_roles manage_workspace_roles),
      'ChorusScope' =>  %w(create show update destroy manage_scopes),
      'User' =>         %w(show change_password edit_dashboard manage_notifications manage_comments manage_notes manage_insights manage_data_source_credentials),
      'Account' =>      %w(create show update destroy change_password lock unlock),
      'Group' =>        %w(create show update destroy),
      'Workspace' =>    %w(create show update destroy admin edit_settings add_members delete_members add_to_scope remove_from_scope change_status explore_data transform_data download_data),
      'DataSource' =>   %w(create show update destroy add_credentials edit_credentials delete_credentials add_data remove_data explore_data download_data),
      'Note' =>         %w(create show update destroy),
      'Schema' =>       %w(create show update destroy),
      'Sandbox' =>      %w(create show update destroy add_to_workspace delete_from_workspace),
      'Comment' =>      %w(create show update destroy promote_to_insight),
      'Workfile' =>     %w(create show update destroy create_workflow run_workflow ),
      'Workflow' =>     %w(create show update destroy run stop open),
      'Job' =>          %w(create show update destroy run stop),
      'Task' =>         %w(create show update destroy run stop),
      'Milestone' =>    %w(create show update destroy complete restart),
      'Tag' =>          %w(create show update destroy apply remove),
      'Upload' =>       %w(create show update destroy),
      'Import' =>       %w(create show update destroy),
      'Notification' => %w(create show update destroy),
      'CsvFile' =>      %w(create show update destroy)
    },

    'collaborator' => {
      'Events::Base' => %w(create_comment_on create_attachment_on),
      'ChorusScope' =>  %w(),
      'Role' =>         %w(),
      'User' =>         %w(),
      'Account' =>      %w(),
      'Group' =>        %w(),
      'Workspace' =>    %w(),
      'DataSource' =>   %w(show),
      'Note' =>         %w(create show),
      'Schema' =>       %w(),
      'Sandbox' =>      %w(),
      'Comment' =>      %w(create show promote_to_insight),
      'Workfile' =>     %w(),
      'Workflow' =>     %w(),
      'Job' =>          %w(),
      'Task' =>         %w(),
      'Milestone' =>    %w(),
      'Tag' =>          %w(create show apply remove),
      'Upload' =>       %w(),
      'Import' =>       %w(),
      'Notification' => %w(),
      'CsvFile' =>      %w()
    },

    'user' => {
      'Events::Base' => %w(create_comment_on create_attachment_on),
      'ChorusScope' =>  %w(),
      'Role' =>         %w(),
      'User' =>         %w(),
      'Account' =>      %w(),
      'Group' =>        %w(),
      'Workspace' =>    %w(),
      'DataSource' =>   %w(show),
      'Note' =>         %w(create show),
      'Schema' =>       %w(),
      'Sandbox' =>      %w(),
      'Comment' =>      %w(create show promote_to_insight),
      'Workfile' =>     %w(),
      'Workflow' =>     %w(),
      'Job' =>          %w(),
      'Task' =>         %w(),
      'Milestone' =>    %w(),
      'Tag' =>          %w(create show apply remove),
      'Upload' =>       %w(),
      'Import' =>       %w(),
      'Notification' => %w(),
      'CsvFile' =>      %w()
    },

    'site_administrator' => {
      'Events::Base' =>  %w(create show update destroy create_comment_on create_attachment_on),
      'ChorusScope' =>   %w(create show update destroy manage_scopes),
      'Role' =>          %w(create show update destroy manage_application_roles manage_workspace_roles),
      'User' =>          %w(create show update destroy change_password edit_dashboard manage_notifications manage_comments manage_notes manage_insights manage_data_source_credentials),
      'Account' =>       %w(create show update destroy change_password lock unlock),
      'Group' =>         %w(create show update destroy),
      'Workspace' =>     %w(create show update destroy admin edit_settings add_members delete_members add_to_scope remove_from_scope  change_status explore_data transform_data download_data),
      'DataSource' =>    %w(create show update destroy add_credentials edit_credentials delete_credentials add_data remove_data explore_data download_data),
      'Note' =>          %w(create show update destroy),
      'Schema' =>        %w(create show update destroy),
      'Sandbox' =>       %w(create show update destroy add_to_workspace delete_from_workspace),
      'Comment' =>       %w(create show update destroy promote_to_insight),
      'Workfile' =>      %w(create show update destroy create_workflow run_workflow),
      'Workflow' =>      %w(create show update destroy run stop open),
      'Job' =>           %w(create show update destroy run stop),
      'Task' =>          %w(create show update destroy run stop),
      'Milestone' =>     %w(create show update destroy complete restart),
      'Tag' =>           %w(create show update destroy apply remove),
      'Upload' =>        %w(create show update destroy),
      'Import' =>        %w(create show update destroy),
      'Notification' =>  %w(create show update destroy),
      'CsvFile' =>       %w(create show update destroy)
    },

    'application_administrator' => {
      'Events::Base' => %w(create show update destroy create_comment_on create_attachment_on),
      'ChorusScope' =>  %w(create show update destroy manage_scopes),
      'Role' =>         %w(create show update destroy manage_application_roles manage_workspace_roles),
      'User' =>         %w(create show update destroy change_password edit_dashboard manage_notifications manage_comments manage_notes manage_insights manage_data_source_credentials),
      'Account' =>      %w(create show update destroy change_password lock unlock),
      'Group' =>        %w(create show update destroy),
      'Workspace' =>    %w(create show update destroy admin edit_settings add_members delete_members add_to_scope remove_from_scope change_status explore_data transform_data download_data),
      'DataSource' =>   %w(create show update destroy add_credentials edit_credentials delete_credentials add_data remove_data explore_data download_data),
      'Note' =>         %w(create show update destroy),
      'Schema' =>       %w(create show update destroy),
      'Sandbox' =>      %w(create show update destroy add_to_workspace delete_from_workspace),
      'Comment' =>      %w(create show update destroy promote_to_insight),
      'Workfile' =>     %w(create show update destroy run_workflow ),
      'Workflow' =>     %w(create show update destroy run stop open),
      'Job' =>          %w(create show update destroy run stop),
      'Task' =>         %w(create show update destroy run stop),
      'Milestone' =>    %w(create show update destroy complete restart),
      'Tag' =>          %w(create show update destroy apply remove),
      'Upload' =>       %w(create show update destroy),
      'Import' =>       %w(create show update destroy),
      'Notification' => %w(create show update destroy),
      'CsvFile' =>      %w(create show update destroy)
    },

    'application_manager' => {
      'Events::Base' => %w(create_comment_on create_attachment_on),
      'ChorusScope' =>  %w(),
      'Role' =>         %w(manage_workspace_roles),
      'User' =>         %w(),
      'Account' =>      %w(),
      'Group' =>        %w(create show update destroy),
      'Workspace' =>    %w(create show update destroy admin edit_settings add_members delete_members add_to_scope remove_from_scope change_status explore_data transform_data download_data),
      'DataSource' =>   %w(create show update destroy add_data remove_data explore_data download_data),
      'Note' =>         %w(create show update destroy),
      'Schema' =>       %w(show),
      'Sandbox' =>      %w(show),
      'Comment' =>      %w(create show update destroy promote_to_insight),
      'Workfile' =>     %w(),
      'Workflow' =>     %w(),
      'Job' =>          %w(),
      'Task' =>         %w(),
      'Milestone' =>    %w(),
      'Tag' =>          %w(create show update destroy apply remove),
      'Upload' =>       %w(create show update destroy),
      'Import' =>       %w(),
      'Notification' => %w(create show update destroy),
      'CsvFile' =>      %w(create show update destroy)
    },

    'workflow_developer' => {
      'Events::Base' =>  %w(),
      'ChorusScope' =>   %w(),
      'Role' =>          %w(),
      'User' =>          %w(),
      'Account' =>       %w(),
      'Group' =>         %w(),
      'Workspace' =>     %w(),
      'DataSource' =>    %w(),
      'Note' =>          %w(),
      'Schema' =>        %w(),
      'Sandbox' =>       %w(),
      'Comment' =>       %w(),
      'Workfile' =>      %w(create create_workflow run_workflow),
      'Workflow' =>      %w(create show update destroy run stop open),
      'Job' =>           %w(),
      'Task' =>          %w(),
      'Milestone' =>     %w(),
      'Tag' =>           %w(),
      'Upload' =>        %w(),
      'Import' =>        %w(),
      'Notification' =>  %w(),
      'CsvFile' =>      %w(create show update destroy)
    },

    'project_manager' => {
      'Events::Base' => %w(create show create_comment_on create_attachment_on),
      'ChorusScope' =>  %w(),
      'Role' =>         %w(),
      'User' =>         %w(),
      'Account' =>      %w(),
      'Group' =>        %w(),
      'Workspace' =>    %w(create show update edit_settings add_members delete_members add_to_scope remove_from_scope change_status explore_data transform_data download_data),
      'DataSource' =>   %w(),
      'Note' =>         %w(create show update destroy),
      'Schema' =>       %w(),
      'Sandbox' =>      %w(),
      'Comment' =>      %w(create show update destroy promote_to_insight),
      'Workfile' =>     %w(create show update destroy run_workflow),
      'Workflow' =>     %w(create show update destroy run stop open),
      'Job' =>          %w(create show update destroy run stop),
      'Task' =>         %w(create show update destroy run stop),
      'Milestone' =>    %w(create show update destroy complete restart),
      'Tag' =>          %w(create show update destroy apply remove),
      'Upload' =>       %w(create show update destroy),
      'Import' =>       %w(create show update destroy),
      'Notification' => %w(create show update destroy),
      'CsvFile' =>      %w(create show update destroy)
    },

    'contributor' => {
      'Events::Base' =>  %w(create show create_comment_on create_attachment_on),
      'ChorusScope' =>   %w(),
      'Role' =>          %w(),
      'User' =>          %w(),
      'Account' =>       %w(),
      'Group' =>         %w(),
      'Workspace' =>     %w(show explore_data transform_data download_data),
      'DataSource' =>    %w(),
      'Note' =>          %w(create show),
      'Schema' =>        %w(),
      'Sandbox' =>       %w(),
      'Comment' =>       %w(create show promote_to_insight),
      'Workfile' =>      %w(create show),
      'Workflow' =>      %w(),
      'Job' =>           %w(create show update destroy run stop),
      'Task' =>          %w(create show update destroy run stop),
      'Milestone' =>     %w(),
      'Tag' =>           %w(create show update destroy apply remove),
      'Upload' =>        %w(create show update destroy),
      'Import' =>        %w(create show update destroy),
      'Notification' =>  %w(create show update destroy),
      'CsvFile' =>       %w(create show update destroy)
    },

    'project_developer' => {
      'Events::Base' => %w(create show create_comment_on create_attachment_on),
      'ChorusScope' =>  %w(),
      'Role' =>         %w(),
      'User' =>         %w(),
      'Account' =>      %w(),
      'Group' =>        %w(),
      'Workspace' =>    %w(create show explore_data transform_data download_data),
      'DataSource' =>   %w(show explore_data download_data),
      'Note' =>         %w(create show),
      'Schema' =>       %w(),
      'Sandbox' =>      %w(),
      'Comment' =>      %w(create show promote_to_insight),
      'Workfile' =>     %w(create show),
      'Workflow' =>     %w(create show update),
      'Job' =>          %w(create show update destroy run stop),
      'Task' =>         %w(create show update destroy run stop),
      'Milestone' =>    %w(),
      'Tag' =>          %w(create show update destroy apply remove),
      'Upload' =>       %w(create show update destroy),
      'Import' =>       %w(create show update destroy),
      'Notification' => %w(create show update destroy),
      'CsvFile' =>      %w(create show update destroy)
    }
  }

  ROLES = ROLE_PERMISSIONS.keys

end
