source "https://rubygems.org"

# Declare your gem's dependencies in core.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

gem 'core', :path => '../core'
gem 'authorization', :path => '../authorization_simpler'

gem 'queue_classic', :github => 'Chorus/queue_classic'
gem 'chorusgnip', :github => 'Chorus/gnip'

gem 'backbone_fixtures_rails', :github => 'charleshansen/backbone_fixtures_rails'
gem 'rspec_api_documentation', :github => 'Chorus/rspec_api_documentation', :require => false
gem "fakefs", :require => "fakefs/safe"
