source 'https://rubygems.org'

# Declare your gems dependencies in admin.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
# gem 'jquery-rails'

gem 'turbolinks'

# Following line is needed only for Rails 3.2.x. In Rails 4 turbolinks in part of core rails.
group :development, :test do
  gem 'adminlte2-rails'
#  gem 'less-rails'
#  gem 'therubyrhino'
end

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem debugger
