development: &development
  database: chorus_core_development
  adapter: jdbcpostgresql
  encoding: unicode
  username: postgres_chorus
  password:
  port: 8543
  min_messages: warning
  host: 127.0.0.1
  pool: 20

test: &TEST
  <<: *development
  database: chorus_core_test